# Generated by Django 3.1.4 on 2021-03-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/user/default_image.jpeg', upload_to='user'),
        ),
    ]
