# Generated by Django 3.1.4 on 2021-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0003_auto_20210304_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
