# Generated by Django 3.1.4 on 2021-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0004_auto_20210311_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
