# Generated by Django 3.1.4 on 2021-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210329_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(blank=True, default='/media/diary/default_image.jpeg', null=True, upload_to='diary'),
        ),
    ]
