# Generated by Django 3.1.4 on 2021-04-02 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypet',
            options={'verbose_name': '펫', 'verbose_name_plural': '펫'},
        ),
        migrations.AlterField(
            model_name='mypet',
            name='birthday',
            field=models.CharField(max_length=15, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='gender',
            field=models.IntegerField(default=2, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='pet_name',
            field=models.CharField(max_length=20, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/pet/default_image.jpeg', null=True, upload_to='pet', verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='species',
            field=models.CharField(max_length=20, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypet', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
