# Generated by Django 3.1.4 on 2021-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0002_auto_20210402_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypet',
            name='birthday',
            field=models.CharField(max_length=15, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='gender',
            field=models.IntegerField(default=2, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='pet_name',
            field=models.CharField(max_length=20, verbose_name='펫 이름'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='profile',
            field=models.CharField(blank=True, max_length=80, verbose_name='프로필 내용'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/pet/default_image.jpeg', null=True, upload_to='pet', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='mypet',
            name='species',
            field=models.CharField(max_length=20, verbose_name='종'),
        ),
    ]
